# Generated by Django 5.1.5 on 2025-03-08 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='education_students', to='configapp.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_students', to='configapp.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
