# Generated by Django 5.1.5 on 2025-03-08 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('studying', 'Studying'), ('graduated', 'Graduated')], default='studying', max_length=20),
        ),
    ]
